<?php
use Illuminate\Database\Seeder;
class Lookupseeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('lookup_masters')->insert([
            ['lookup_key' => 'Master','lookup_value'    =>'UNIT','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'ITEM CATEGORY','lookup_description'    =>'item table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'SEX','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'CURRENCY','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'COUNTRY','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'TAX','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'DEPARTMENT','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'PURCHASE ORDER TERMS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'EARNING AND DEDUCTION','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'EMPLOYEE STATUS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'COUNTER','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'COMPONENT OPERATIONS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'STORE','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'PRODUCT CATEGORY','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'BIN TRANSACTIONS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'CLIENT REGION','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'BANK','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'MACHINE MODEL','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'DOCUMENT THROUGH','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'MODE OF DESPATCH','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'PURCHASE ORDER SHORT CLOSE RESON','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'DISTRICTS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'STATES','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'CUSTOMER CLASS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'MODE OF DISPATCH','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'MODE OF PAYMENT','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'TYPE OF CONE','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'TUBE SIZE','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'MODE OF ENQUIRY','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'PRODUCT FAMILY','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'MACHINE LOCATION','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'MARTIAL STATUS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'EMPLOYEE CLASS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'SPARE ORDER TYPE','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'DESIGNATION','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'CROSSING RATIO','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'RELIGION','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'VENDOR CLASS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'BLOOD GROUP','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'MACHINE COLOR','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'TRAY','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'THREAD GUIDES','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'ITEMS STATUS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'MOTOR','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'LUBRICATING SYSTEM','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'NO OF LAYS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'TYPE OF PACKING','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'CONTROLS','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
            ['lookup_key' => 'Master','lookup_value'    =>'PULLY ','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
          ['lookup_key' => 'Master','lookup_value'    =>'YARN COUNT','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
          ['lookup_key' => 'Master','lookup_value'    =>'YARN QUALITY ','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
          ['lookup_key' => 'Master','lookup_value'    =>'YARN TYPE ','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],
          ['lookup_key' => 'Master','lookup_value'    =>'YARN PROCESS ','lookup_description'    =>'unit table','genaral_value'    =>'unit table'],


             ['lookup_key' => 'UNIT','lookup_value'    =>'Kg' ,'lookup_description'    =>'Kilogram',   'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'UNIT','lookup_value'    =>'No' ,'lookup_description'    =>'Number',     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'UNIT','lookup_value'    =>'Mts','lookup_description'    =>'Meter' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'UNIT','lookup_value'    =>'Gm' ,'lookup_description'    =>'Gram'  ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'UNIT','lookup_value'    =>'Ltr','lookup_description'    =>'Liter' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'UNIT','lookup_value'    =>'Rol' ,'lookup_description'    =>'Roll' ,     'genaral_value'    =>'unit table'],
             ['lookup_key' => 'UNIT','lookup_value'    =>'Ches' ,'lookup_description'    =>'Chees' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'UNIT','lookup_value'    =>'Box' ,'lookup_description'    =>'BOX' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'UNIT','lookup_value'    =>'Bag' ,'lookup_description'    =>'Bag' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'UNIT','lookup_value'    =>'Tube' ,'lookup_description'    =>'Tube' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'UNIT','lookup_value'    =>'Barl' ,'lookup_description'    =>'Barel' ,     'genaral_value'    =>'unit table'], 
             ['lookup_key' => 'UNIT','lookup_value'    =>'Cone' ,'lookup_description'    =>'Cone' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'UNIT','lookup_value'    =>'Cops' ,'lookup_description'    =>'Cops' ,     'genaral_value'    =>'unit table'],  
      
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'DYE' ,'lookup_description'  =>'Dyes' , 'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'CHEM' ,'lookup_description'  =>'Chemicals' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'PACK' ,'lookup_description'  =>'Packing Materias' ,'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'CONS' ,'lookup_description'  =>'Consumables' ,           'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'FASTN' ,'lookup_description'  =>'Fastners' ,          'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'MECH' ,'lookup_description'  =>'Mechanical Items' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'SPARE' ,'lookup_description'  =>'Spare parts' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'BOILR' ,'lookup_description'  =>'Boiler Consumables' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'GREY' ,'lookup_description'  =>'Grey Yarn' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'DYED' ,'lookup_description'  =>'Dyed Yarn' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'PCOP' ,'lookup_description'  =>'Plain Cops' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'LBCOP' ,'lookup_description'  =>'Labeld Cops' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'PBOX' ,'lookup_description'  =>'Packed Boxes' ,     'genaral_value'    =>'unit table'],        
             ['lookup_key' => 'ITEM CATEGORY','lookup_value'    =>'SAFTY' ,'lookup_description'  =>'Safty Items' ,     'genaral_value'    =>'unit table'],
        
            ['lookup_key' => 'SEX','lookup_value'    =>'M' ,'lookup_description'  =>'Male' ,     'genaral_value'    =>'unit table'],        
            ['lookup_key' => 'SEX','lookup_value'    =>'F' ,'lookup_description'  =>'Female' ,     'genaral_value'    =>'unit table'],   
     
            ['lookup_key' =>  'SEX','lookup_value'    =>'O' ,'lookup_description'  =>'Other' ,     'genaral_value'    =>'unit table'],        
            ['lookup_key' => 'CURRENCY','lookup_value'    =>'INR' ,'lookup_description'  =>'Indian Rupees' ,         'genaral_value'    =>'1'],        
            ['lookup_key' => 'CURRENCY','lookup_value'    =>'ADOLR' ,'lookup_description'  =>'American Dollar' ,     'genaral_value'    =>'70'],        
            ['lookup_key' => 'CURRENCY','lookup_value'    =>'EURO' ,'lookup_description'  =>'European Euro' ,        'genaral_value'    =>'80'],        
            ['lookup_key' => 'CURRENCY','lookup_value'    =>'DIRHM' ,'lookup_description'  =>'UAE Dinar' ,          'genaral_value'     =>'19'],        
            ['lookup_key' => 'CURRENCY','lookup_value'    =>'RIYAL' ,'lookup_description'  =>'Saudi Riyal' ,        'genaral_value'     =>'20'],        
            ['lookup_key' => 'CURRENCY','lookup_value'    =>'DINR' ,'lookup_description'  =>'Kuwait Dinar' ,        'genaral_value'     =>'112'], 
            ['lookup_key' => 'CURRENCY','lookup_value'    =>'YEN' ,'lookup_description'  =>'Japan Yen' ,            'genaral_value'     =>'0.71'],        
            ['lookup_key' => 'CURRENCY','lookup_value'    =>'YUVAN' ,'lookup_description'  =>'Chinees Yuvan' ,      'genaral_value'     =>'11.25'],        
            ['lookup_key' => 'CURRENCY','lookup_value'    =>'RUBL' ,'lookup_description'  =>'Russian Ruble' ,        'genaral_value'     =>'0.97'],        
            ['lookup_key' => 'CURRENCY','lookup_value'    =>'ASDLR' ,'lookup_description'  =>'Australian Dollar' ,   'genaral_value'     =>'54.62'],        
                  
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'IND' ,'lookup_description'  =>'India' ,           'genaral_value'    =>' '],        
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'AMRCA' ,'lookup_description'  =>'America' ,        'genaral_value'    =>''],        
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'AUSTR' ,'lookup_description'  =>'Australia' ,      'genaral_value'    =>''],        
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'EURP' ,'lookup_description'  =>'Europe' ,          'genaral_value'    =>''],        
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'AFRIc' ,'lookup_description'  =>'Africa' ,        'genaral_value'    =>''],        
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'UAE' ,'lookup_description'  =>'Uae' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'SRIL' ,'lookup_description'  =>'Sri Lanka' ,        'genaral_value'    =>''],        
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'PAKN' ,'lookup_description'  =>'Pakistan' ,        'genaral_value'    =>''],        
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'SAUDI' ,'lookup_description'  =>'Saudi Arabia' , 'genaral_value'    =>''],        
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'CHINA' ,'lookup_description'  =>'China' ,        'genaral_value'    =>''],        
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'KUWT' ,'lookup_description'  =>'Kuwait' ,        'genaral_value'    =>''],         
            ['lookup_key' => 'COUNTRY','lookup_value'    =>'JAPN' ,'lookup_description'  =>'Japan' ,         'genaral_value'    =>''],
         
            ['lookup_key' => 'TAX','lookup_value'    =>'GST18' ,'lookup_description'  =>'GST 18%' ,         'genaral_value'    =>'18'],        
            ['lookup_key' => 'TAX','lookup_value'    =>'GST28' ,'lookup_description'  =>'GST 28%' ,         'genaral_value'    =>'28'],        
            ['lookup_key' => 'TAX','lookup_value'    =>'GST12' ,'lookup_description'  =>'GST 12%' ,         'genaral_value'    =>'12'],        
            ['lookup_key' => 'TAX','lookup_value'    =>'GST5' ,'lookup_description'  =>'GST 5%' ,         'genaral_value'    =>'5'],        
            ['lookup_key' => 'TAX','lookup_value'    =>'IGST18' ,'lookup_description'  =>'IGST 18%' ,         'genaral_value'    =>'18'],        
            ['lookup_key' => 'TAX','lookup_value'    =>'IGST28' ,'lookup_description'  =>'IGST 28%' ,         'genaral_value'    =>'28'],        
            ['lookup_key' => 'TAX','lookup_value'    =>'IGST12' ,'lookup_description'  =>'IGST 12%' ,         'genaral_value'    =>'12'],        
            ['lookup_key' => 'TAX','lookup_value'    =>'IGST5' ,'lookup_description'  =>'IGST 5%' ,         'genaral_value'    =>'5'],
            ['lookup_key' => 'TAX','lookup_value'    =>'P&F' ,'lookup_description'  =>'Packing and Forwarding' , 'genaral_value'    =>''],
            ['lookup_key' => 'TAX','lookup_value'    =>'COUR' ,'lookup_description'  =>'Courrier Charges' ,         'genaral_value'    =>''],
            ['lookup_key' => 'TAX','lookup_value'    =>'HAND' ,'lookup_description'  =>'Handling Charges' ,         'genaral_value'    =>''],        
            ['lookup_key' => 'TAX','lookup_value'    =>'TCS' ,'lookup_description'  =>'TCS ' ,             'genaral_value'    =>''],        
           
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'ADM' ,'lookup_description'  =>'Administration' ,   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'PURCH' ,'lookup_description'  =>'Purchase' ,   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'STORE' ,'lookup_description'  =>'Stores' ,   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'PPC' ,'lookup_description'  =>'Production Planning and Control',   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'RND' ,'lookup_description'  =>'Research and Development' ,   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'IQC' ,'lookup_description'  =>'Inspection and QC' ,   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'MSHP' ,'lookup_description'  =>'Machine Shope' ,   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'ASSY' ,'lookup_description'  =>'Assembly' ,      'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'FINA' ,'lookup_description'  =>'Finance' ,   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'WET' ,'lookup_description'  =>'Wet Processing' ,   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'WIND' ,'lookup_description'  =>'Winding' ,   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'PACK' ,'lookup_description'  =>'Packing' ,   'genaral_value'    =>''],
         ['lookup_key' => 'DEPARTMENT','lookup_value'    =>'SUB' ,'lookup_description'  =>'Sub Contact' ,   'genaral_value'    =>''],
         
         ['lookup_key' => 'PURCHASE ORDER TERMS','lookup_value'    =>'ADV100' ,'lookup_description'  =>'Payment' ,   'genaral_value'    =>'100 % Advance'],
         ['lookup_key' => 'PURCHASE ORDER TERMS','lookup_value'    =>'ASUP' ,'lookup_description'  =>'Payment' ,   'genaral_value'    =>'Against Supply'],
         ['lookup_key' => 'PURCHASE ORDER TERMS','lookup_value'    =>'CRE30','lookup_description'  =>'Payment' ,   'genaral_value'    =>'30 Days Credit'],
         ['lookup_key' => 'PURCHASE ORDER TERMS','lookup_value'    =>'CRE30','lookup_description'  =>'Deleivery' ,   'grenaral_value'    =>'At our Factory site'],
         ['lookup_key' => 'PURCHASE ORDER TERMS','lookup_value'    =>'CRE30','lookup_description'  =>'Deleivery' ,   'grenaral_value'    =>'We will collect'],
         ['lookup_key' => 'PURCHASE ORDER TERMS','lookup_value'    =>'CRE30','lookup_description'  =>'Deleivery' ,   'grenaral_value'    =>'As per previous suppy'],
        
            ['lookup_key' => 'BIN TRANSACTIONS','lookup_value'    =>'10' ,'lookup_description'  =>'Openint Stock ' ,                  'genaral_value'    =>''],        
            ['lookup_key' => 'BIN TRANSACTIONS','lookup_value'    =>'11' ,'lookup_description'  =>'Receipt assembly ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'BIN TRANSACTIONS','lookup_value'    =>'20' ,'lookup_description'  =>'Receipt From Customer' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'BIN TRANSACTIONS','lookup_value'    =>'30' ,'lookup_description'  =>'Stock Correction(+) ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'BIN TRANSACTIONS','lookup_value'    =>'40' ,'lookup_description'  =>'Receipt Purchase ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'BIN TRANSACTIONS','lookup_value'    =>'50' ,'lookup_description'  =>'Reciept Production' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'BIN TRANSACTIONS','lookup_value'    =>'60' ,'lookup_description'  =>'Issue Store Request ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'BIN TRANSACTIONS','lookup_value'    =>'70' ,'lookup_description'  =>'Issue Sub Contact DC ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'BIN TRANSACTIONS','lookup_value'    =>'80' ,'lookup_description'  =>'Issue General DC ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'BIN TRANSACTIONS','lookup_value'    =>'90' ,'lookup_description'  =>'Stock Adjustment (-) ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'STORE','lookup_value'    =>'01' ,'lookup_description'  =>'Main Store ' ,    'genaral_value'    =>''],        
            ['lookup_key' => 'STORE','lookup_value'    =>'02' ,'lookup_description'  =>'WIP ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'STORE','lookup_value'    =>'03' ,'lookup_description'  =>'Spare Store ' ,             'genaral_value'    =>''],        
          
            ['lookup_key' => 'DISTRICTS','lookup_value'    =>'COH' ,'lookup_description'  =>'Ernakuam',       'genaral_value'    =>''],        
            ['lookup_key' => 'DISTRICTS','lookup_value'    =>'PALG' ,'lookup_description'  =>'Palakkad',       'genaral_value'    =>''],        
            ['lookup_key' => 'DISTRICTS','lookup_value'    =>'TRVM' ,'lookup_description'  =>'Trivandrum',       'genaral_value'    =>''],        
            ['lookup_key' => 'DISTRICTS','lookup_value'    =>'CBE' ,'lookup_description'  =>'Coimbatore',      'genaral_value'    =>''],        
            ['lookup_key' => 'DISTRICTS','lookup_value'    =>'EROD' ,'lookup_description'  =>'Erode ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'DISTRICTS','lookup_value'    =>'SALM' ,'lookup_description'  =>'Salem ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'DISTRICTS','lookup_value'    =>'THENI' ,'lookup_description'  =>'Theni ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'DISTRICTS','lookup_value'    =>'CHEN' ,'lookup_description'  =>'Chennai ' ,             'genaral_value'    =>''],        
            ['lookup_key' => 'DISTRICTS','lookup_value'    =>'BGLR' ,'lookup_description'  =>'Bangalore ' ,             'genaral_value'    =>''],        
          ['lookup_key' => 'STATES','lookup_value'    =>'TN' ,'lookup_description'  =>'Tamil nadu ' ,             'genaral_value'    =>''],        
          ['lookup_key' => 'STATES','lookup_value'    =>'KERL' ,'lookup_description'  =>'Kerala' ,             'genaral_value'    =>''],        
          ['lookup_key' => 'STATES','lookup_value'    =>'KARN' ,'lookup_description'  =>'Karnataka ' ,             'genaral_value'    =>''],        
          ['lookup_key' => 'STATES','lookup_value'    =>'DELH' ,'lookup_description'  =>'Delhi ' ,             'genaral_value'    =>''],        
          
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT1B' ,'lookup_description'  =>'119 DTEX X 2 BLACK ', 'genaral_value'    =>'SSPD01192QJR'],        
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT2B' ,'lookup_description'  =>'98 DTEX X 3 BLACK' ,'genaral_value'    =>'SSPD00983QJR'],        
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT3W' ,'lookup_description'  =>'147 DTEX X2 WHITE' ,'genaral_value'    =>'OBPE01472QJS'],        
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT2W' ,'lookup_description'  =>'98 DTEX X 3 WHITE' ,'genaral_value'    =>'OBPE00983QJS'],        
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT1W' ,'lookup_description'  =>'119 DTEX X 2 WHITE' , 'genaral_value'    =>'OBPE01192QJS'],        
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT4' ,'lookup_description'  =>'90 DTEX X 2' ,         'genaral_value'    =>'SSPA0090295R'],        
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT6' ,'lookup_description'  =>'110 DTEX X 2' ,         'genaral_value'    =>'SSPB0110295R'],        
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT10' ,'lookup_description'  =>'110 DTEX X 3' ,         'genaral_value'    =>'SSPB0110395R'],        
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT1' ,'lookup_description'  =>'119 DTEX X 2' ,         'genaral_value'    =>'SSPE0119295R'],        
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT2' ,'lookup_description'  =>'98 DTEX X 3' ,         'genaral_value'    =>'SSPE0098395R'],        
          ['lookup_key' => 'YARN COUNT','lookup_value'    =>'CNT3' ,'lookup_description'  =>'147 DTEX X2' ,         'genaral_value'    =>'SSPB0147295R'],
        
          ['lookup_key' => 'YARN QUALITY','lookup_value'    =>'GREY' ,'lookup_description'  =>'Grey' ,         'genaral_value'    =>'GR'],        
          ['lookup_key' => 'YARN QUALITY','lookup_value'    =>'DYBLK' ,'lookup_description'  =>'Dyed Black ' ,  'genaral_value'    =>'DB'],        
          ['lookup_key' => 'YARN QUALITY','lookup_value'    =>'LCOP' ,'lookup_description'  =>'Labled Cop' ,  'genaral_value'    =>'LC'],        
          ['lookup_key' => 'YARN QUALITY','lookup_value'    =>'PACK' ,'lookup_description'  =>'Packed Box'  ,  'genaral_value'    =>'PK'],        
          ['lookup_key' => 'YARN QUALITY','lookup_value'    =>'PCOP' ,'lookup_description'  =>'Plain Cop' ,    'genaral_value'    =>'PC'],        
          ['lookup_key' => 'YARN QUALITY','lookup_value'    =>'DYED' ,'lookup_description'  =>'Dyed' ,         'genaral_value'    =>'DY'],        
          ['lookup_key' => 'YARN QUALITY','lookup_value'    =>'DDYED' ,'lookup_description'  =>'Dope Dyed' ,   'genaral_value'    =>'DD'],        
          ['lookup_key' => 'YARN QUALITY','lookup_value'    =>'OPT1' ,'lookup_description'  =>'Opt1' ,         'genaral_value'    =>'OP'],        
          
          ['lookup_key' => 'YARN TYPE','lookup_value'    =>'POL' ,'lookup_description'  =>'Polyster' ,        'genaral_value'    =>''],        
          ['lookup_key' => 'YARN TYPE','lookup_value'    =>'COT' ,'lookup_description'  =>'Cotton' ,         'genaral_value'    =>''],        
          
           ['lookup_key' => 'YARN PROCESS','lookup_value'    =>'DyE' ,'lookup_description'  =>'Dyeing' ,         'genaral_value'    =>'DYEV'],        
           ['lookup_key' => 'YARN PROCESS','lookup_value'    =>'TWNG' ,'lookup_description'  =>'Tube Winding' ,   'genaral_value'    =>'TWMC'],        
           ['lookup_key' => 'YARN PROCESS','lookup_value'    =>'BAND' ,'lookup_description'  =>'Cop Banding' ,    'genaral_value'    =>'COPB'],        
           ['lookup_key' => 'YARN PROCESS','lookup_value'    =>'PACK' ,'lookup_description'  =>'Packing' ,         'genaral_value'    =>'HAND'],        
          
          ['lookup_key' => 'MODE OF ENQUIRY','lookup_value'    =>'ENQM' ,'lookup_description'  =>'Marketting' ,         'genaral_value'    =>''],        
          ['lookup_key' => 'MODE OF ENQUIRY','lookup_value'    =>'EMAI' ,'lookup_description'  =>'E-mail' ,         'genaral_value'    =>''],        
          ['lookup_key' => 'MODE OF ENQUIRY','lookup_value'    =>'ETEL' ,'lookup_description'  =>'Telephonic' ,         'genaral_value'    =>''],        
          ['lookup_key' => 'MODE OF ENQUIRY','lookup_value'    =>'EEMD' ,'lookup_description'  =>'Electronic Media' ,    'genaral_value'    =>''],        
          
          ['lookup_key' => 'ITEMS STATUS','lookup_value'    =>'A' ,'lookup_description'  =>'Active' ,      'genaral_value'    =>''],        
          ['lookup_key' => 'ITEMS STATUS','lookup_value'    =>'I' ,'lookup_description'  =>'In Active' ,    'genaral_value'    =>''],        
          



 
        ]);
    }
}